<h1>We meet again. 👋</h1>

<p>One day I tweeted that I would begin writing more about the work that I do, so I created a home on the web for that, and this is where that stuff lives.</p>

<p>I am currently a Front-End Developer and Designer working at <a href="http://cardinalsolutions.com" alt="Cardinal Solutions">Cardinal Solutions</a> in the beautiful city of Columbus, Ohio. There I create meaningful and engaging experiences under our UX roof. I've worked on a wide range of projects for <a href="http://highlights.com" alt="Highlights for Children">Highlights</a>, <a href="http://mycumortage.com" alt="Wright-Patt Credit Union's myCUmortgage">Wright-Patt</a>, <a href="https://davethomasfoundation.org" alt="Dave Thomas Foundation">Dave Thomas Foundation</a>, and more!</p>

<p>Before that, I was an Apprentice at <a href="http://seesparkbox.com" alt="Sparkbox">Sparkbox</a> where I learned a great deal about web development and it's best practices. 👏 I also ate a lot of Oreos there – <strong>a whole lot</strong> of Oreos. And prior to that, I worked at a small SaaS startup in Chicago, where I wore many hats 🎩✨, working on client sites, assets, wireframes – you name it.</p>

<p>I am passionate about creating experiences that are accessible and easy to use for all. I am perpetual learner and I don't just learn, I obsess.</p>

<p>If you'd like to know more, please feel free to <a href="mailto:hello@laurendorman.io" alt="Email me at hello@laurendorman.io">contact</a> or <a href="https://twitter.com/laurendorman" alt="Follow @LaurenDorman on Twitter">follow</a> me. I'm all over the web.</p>