<footer id="footer">
  <p class='footer__text'>&copy; 2016 &middot; Packaged with care.</p>
  <ul class="footer__nav">
  	<li><a href="https://github.com/laurendorman/laurendorman.github.io/tree/dev" alt="Source code for laurendorman.io">Source</a></li>
  	<li><a href="/style-guide" alt="Code style guide by Lauren Dorman">Style Guide</a></li>
  	<li><a href="/colophon" alt="Colophon for laurendorman.io">Colophon</a></li>
  </ul>
</footer>